

FROM golang:1.18-alpine AS builder
LABEL stage=builder

WORKDIR /app

COPY app/go.mod ./
COPY app/go.sum ./
RUN go mod download
COPY app/*.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-p2p-test

FROM alpine AS final

ARG ENV
ENV SERVICE_NAME=peer1
WORKDIR /

COPY --from=builder /docker-p2p-test .

CMD [ "./docker-p2p-test", "-port", "6000", "-peer", "/dns4/host/tcp/6000/p2p/QmcMEhoGw96nxRznstN8sQZGDT4rJxwh7nxCba6U1pQye1", "-seed", "989"]