name: peer-nn-env
channels:
  - conda-forge
  - defaults
dependencies:
  - pip==22.2.2
  - python==3.9
  - pip:
    - ipykernel==6.16.0
    - numpy==1.23.3
    - torch==1.12.1
    - tqdm==4.64.0
    - matplotlib==3.5.2
    - scikit-learn==1.1.2
    - mlxtend==0.20.0
    - sqlitedict==2.0.0
    - pytest==7.1.3
    - pyarrow==9.0.0
